/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3HUGjkFtDYKkVe7ziow89U
// Component: -3BVGIuEyPIp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Icon from "../../Icon"; // plasmic-import: lRs69RVE1bNJ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 3HUGjkFtDYKkVe7ziow89U/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 3HUGjkFtDYKkVe7ziow89U/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicLogo2.module.css"; // plasmic-import: -3BVGIuEyPIp/css

createPlasmicElementProxy;

export type PlasmicLogo2__VariantMembers = {
  primary: "primary";
};
export type PlasmicLogo2__VariantsArgs = {
  primary?: SingleBooleanChoiceArg<"primary">;
};
type VariantPropType = keyof PlasmicLogo2__VariantsArgs;
export const PlasmicLogo2__VariantProps = new Array<VariantPropType>("primary");

export type PlasmicLogo2__ArgsType = { children?: React.ReactNode };
type ArgPropType = keyof PlasmicLogo2__ArgsType;
export const PlasmicLogo2__ArgProps = new Array<ArgPropType>("children");

export type PlasmicLogo2__OverridesType = {
  row?: Flex__<"div">;
  icon?: Flex__<typeof Icon>;
  freeBox?: Flex__<"div">;
};

export interface DefaultLogo2Props {
  children?: React.ReactNode;
  primary?: SingleBooleanChoiceArg<"primary">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogo2__RenderFunc(props: {
  variants: PlasmicLogo2__VariantsArgs;
  args: PlasmicLogo2__ArgsType;
  overrides: PlasmicLogo2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "primary",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.primary
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"row"}
      data-plasmic-override={overrides.row}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_3HUGjkFtDYKkVe7ziow89U",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.row,
        { [sty.rowprimary]: hasVariant($state, "primary", "primary") }
      )}
    >
      <Icon
        data-plasmic-name={"icon"}
        data-plasmic-override={overrides.icon}
        className={classNames("__wab_instance", sty.icon, {
          [sty.iconprimary]: hasVariant($state, "primary", "primary")
        })}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div
                className={classNames(
                  "all",
                  "__wab_text",
                  sty.text__nxcw6,
                  "distressed-text"
                )}
              >
                {"PROJECT"}
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__pmz3I)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"350px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/4321/images/безНазванияPng.png",
                  fullWidth: 298,
                  fullHeight: 120,
                  aspectRatio: undefined
                }}
              />
            </React.Fragment>
          ),
          value: args.children
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  row: ["row", "icon", "freeBox"],
  icon: ["icon"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  row: "div";
  icon: typeof Icon;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogo2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogo2__VariantsArgs;
    args?: PlasmicLogo2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogo2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogo2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogo2__ArgProps,
          internalVariantPropNames: PlasmicLogo2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogo2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "row") {
    func.displayName = "PlasmicLogo2";
  } else {
    func.displayName = `PlasmicLogo2.${nodeName}`;
  }
  return func;
}

export const PlasmicLogo2 = Object.assign(
  // Top-level PlasmicLogo2 renders the root element
  makeNodeComponent("row"),
  {
    // Helper components rendering sub-elements
    icon: makeNodeComponent("icon"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicLogo2
    internalVariantProps: PlasmicLogo2__VariantProps,
    internalArgProps: PlasmicLogo2__ArgProps
  }
);

export default PlasmicLogo2;
/* prettier-ignore-end */
