/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3HUGjkFtDYKkVe7ziow89U

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_4N5A78LQohMz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 4n5A78LQohMz/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_4N5A78LQohMz
});
