/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3HUGjkFtDYKkVe7ziow89U
// Component: Y9vfs6E7GKqg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import SecondatyLogo from "../../SecondatyLogo"; // plasmic-import: -3BVGIuEyPIp/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 3HUGjkFtDYKkVe7ziow89U/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 3HUGjkFtDYKkVe7ziow89U/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicPrimaryLogo.module.css"; // plasmic-import: Y9vfs6E7GKqg/css

createPlasmicElementProxy;

export type PlasmicPrimaryLogo__VariantMembers = {};
export type PlasmicPrimaryLogo__VariantsArgs = {};
type VariantPropType = keyof PlasmicPrimaryLogo__VariantsArgs;
export const PlasmicPrimaryLogo__VariantProps = new Array<VariantPropType>();

export type PlasmicPrimaryLogo__ArgsType = {};
type ArgPropType = keyof PlasmicPrimaryLogo__ArgsType;
export const PlasmicPrimaryLogo__ArgProps = new Array<ArgPropType>();

export type PlasmicPrimaryLogo__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  secondatyLogo?: Flex__<typeof SecondatyLogo>;
};

export interface DefaultPrimaryLogoProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPrimaryLogo__RenderFunc(props: {
  variants: PlasmicPrimaryLogo__VariantsArgs;
  args: PlasmicPrimaryLogo__ArgsType;
  overrides: PlasmicPrimaryLogo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_3HUGjkFtDYKkVe7ziow89U",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        <SecondatyLogo
          data-plasmic-name={"secondatyLogo"}
          data-plasmic-override={overrides.secondatyLogo}
          className={classNames("__wab_instance", sty.secondatyLogo)}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "secondatyLogo"],
  freeBox: ["freeBox", "secondatyLogo"],
  secondatyLogo: ["secondatyLogo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  secondatyLogo: typeof SecondatyLogo;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPrimaryLogo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPrimaryLogo__VariantsArgs;
    args?: PlasmicPrimaryLogo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPrimaryLogo__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPrimaryLogo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPrimaryLogo__ArgProps,
          internalVariantPropNames: PlasmicPrimaryLogo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPrimaryLogo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPrimaryLogo";
  } else {
    func.displayName = `PlasmicPrimaryLogo.${nodeName}`;
  }
  return func;
}

export const PlasmicPrimaryLogo = Object.assign(
  // Top-level PlasmicPrimaryLogo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    secondatyLogo: makeNodeComponent("secondatyLogo"),

    // Metadata about props expected for PlasmicPrimaryLogo
    internalVariantProps: PlasmicPrimaryLogo__VariantProps,
    internalArgProps: PlasmicPrimaryLogo__ArgProps
  }
);

export default PlasmicPrimaryLogo;
/* prettier-ignore-end */
