/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3HUGjkFtDYKkVe7ziow89U

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 3HUGjkFtDYKkVe7ziow89U/projectModule

const data = {
  base: `${"plasmic_tokens_3HUGjkFtDYKkVe7ziow89U"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
